-- 1. CREATE ADMINS TABLE
CREATE TABLE IF NOT EXISTS admins (
    id uuid primary key default gen_random_uuid(),
    name varchar(100) not null,
    email varchar(255) unique not null,
    password_hash text not null,
    is_active boolean default true,
    refresh_token text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- 2. RE-ADD ADMIN FOREIGN KEYS to DISPUTES & SKILL_VERIFICATIONS
ALTER TABLE skill_verifications ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES admins(id);
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS resolved_by uuid REFERENCES admins(id);

-- 3. RLS POLICIES & TRIGGERS
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER set_admins_updated_at BEFORE UPDATE ON admins FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

-- Admins policies (Admins can read/update their own profile)
CREATE POLICY "Admins can read own profile" ON admins FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY "Admins can update own profile" ON admins FOR UPDATE TO authenticated USING (id = auth.uid());

-- Insert a default admin for testing (password is 'admin123')
-- Hash generated by bcrypt(admin123)
INSERT INTO admins (name, email, password_hash) 
VALUES ('Super Admin', 'admin@sewasahayog.com', '$2b$10$C8.qU6E7vN3JkE9/xYqWz.3aXWb9jV9LdM/e5R8M2zY5K4V9rR4O6') 
ON CONFLICT (email) DO NOTHING;
